#pragma config(Hubs,  S1, HTServo,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Servo,  srvo_S1_C1_1,    pushR,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    pushL,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    clampR,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    clampL,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_1,    liftR,                tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    liftL,                tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//tube lift defalt upward
//clamp defalt downward
//defalt when game starts
//only goes down when buttons are pressed
//clamps goes up when lift goes down
//clamps only functional when open
//look at toggle genral and fsm or fma
//toggle, push, delay
#include "JoystickDriver.c"

float map(float rLower, float rUpper, float dLower, float dUpper, float dVal)
{
	return (dVal - dLower) * (rUpper - rLower) / (dUpper - dLower)+rLower;
}

task main()
{
	bool togglePlate = false;
	bool toggleClamp = false;
	bool plateOpen = false;
	bool clampDown = false;
	servo[liftR] = 255;
	servo[liftL] = 5;
	servo[clampL] = 255;
	servo[clampR] = 0;
	while(true) //infinate loop
	{
		getJoystickSettings(joystick); //gets joystick settings
		if(joy1Btn(01))//if button 1 is pressed...
		{
			if(!togglePlate)
			{
				if(plateOpen)
				{
					servo[clampL] = 255; //clampL will be at the 255 position
					servo[clampR] = 0; //clampR will be at the 0 position
					servo[liftR] = 255; //liftR will be a the 255 position
					servo[liftL] = 5; //liftL will be at the 5 position 
				}
				else //if not...
				{
					servo[liftR] = 50;//the liftR, liftL, clampL, and clampR will be set to the default 
					servo[liftL] = 220;
					servo[clampL] = 0;
					servo[clampR] = 255;
				}
				plateopen = !plateopen;
			}
			togglePlate = true;
		}
		else
		{
			togglePlate = false;
		}
		if (joy1Btn(03)||joy1Btn(02))//if the button 3 or button 2 are pressed, then clampL will be at 0 position and clampR 255 (the clamp servos will make the clamps go up 
		{
			if(!toggleClamp)
			{
				if(clampDown)
				{
					servo[clampL] = 0;
					servo[clampR] = 255;
				}
				else //if the buttons aren't pushed, then the servos will remain at their default positions
				{
					servo[clampL] = 255;
					servo[clampR] = 0;
				}
				clampDown = !clampDown;
			}
			toggleClamp = true;
		}
		else
		{
			toggleClamp = false;
		}
		if (joy1Btn(02))//if button 2 is pushed, then the servo: pushR is at the position 175 and pushL is at the position 75 which has the push servos go in
		{
			if(clampDown)
			{
				wait10Msec(100);
			}
			servo[pushR] = 175;
			servo[pushL] = 75;
		}
		else//the servos will be at the default position
		{
			servo[pushR] = 5;
			servo[pushL] = 235;
		}
	}
}

/*writeDebugStreamLine("%f, %f", map(0, 255, 0, 128, joystick.joy1_y1),map(0, 255, 128, 0, joystick.joy1_y1));
if(joy1Btn(4))
{
//servo[pushR] = map(5, 175, 0, 128, joystick.joy1_y1);
//servo[pushL] = map(75, 235, 128, 0, joystick.joy1_y1);
servo[pushR] = 175;
servo[pushL] = 75;
}
else
{
servo[pushR] = 5;
servo[pushL] = 235;
}
servo[liftR] = map(50, 255, 0, 128, joystick.joy1_y2);
servo[liftL] = map(5, 220, 128, 0, joystick.joy1_y2);
servo[clampR] = map(0, 255, 128, 0, joystick.joy1_y1);
servo[clampL] = map(0, 255, 0, 128, joystick.joy1_y1);*/
