#pragma config(Motor,  motorA,          motorRight,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          motorLeft,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//width = 4
void move(int wheelRadius, int widthBetweenWheels, int power) {
	motor[motorLeft]=power;
	motor[motorRight]=power*((2*wheelRadius+widthBetweenWheels)/(2*wheelRadius-widthBetweenWheels));
}

//r is in inches
void moveCircle(int radius) {
	nMotorEncoder[motorLeft] = 0;
	nMotorEncoder[motorRight] = 0;
	int circum = PI*(2*radius);
	writeDebugStreamLine("circum: %d", circum);
	int revol = ((circum) / (2*PI));
	writeDebugStreamLine("revol: %d", revol);
	long encoder = revol*360;
	writeDebugStreamLine("encoder: %d", encoder);
	while (nMotorEncoder[motorRight] <= encoder) {
		move(1,4,50);
	}
}



task main()
{
	moveCircle(100);
}