#pragma config(Sensor, S1,     IR,             sensorHiTechnicIRSeeker1200)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-irseeker-v2.h"

tHTIRS2 IRSENSE;

task main()
{
	initSensor(&IRSENSE, S1);
	while(true)
	{
		readSensor(&IRSENSE);
		nxtDisplayTextLine(1, "%a", IRSENSE.acValues);
		wait10Msec(100);
	}
}
