#pragma config(Sensor, S1,     IR,             sensorHiTechnicIRSeeker1200)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-irseeker-v2.h"

tHTIRS2 irSeeker;
irSeeker.mode = DSP_1200;

task main()
{
	initSensor(&irSeeker, S1);
	while(true)
	{
		readSensor(&irSeeker);
		for(int n = 0; n < 5; n++)
		{
			nxtDisplayTextLine(n+1, "%d", irSeeker.acValues[n]);
		}
		sleep(1000);
	}
}
