#pragma config(Sensor, S1,     ultraSonic,     sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		float ultrasonicInchReading = SensorValue(ultraSonic)/2.54;
		displayCenteredTextLine(3, "%d", ultrasonicInchReading);
		wait1Msec(10);
		eraseDisplay();
	}
}
