#pragma config(Hubs,  S1, HTServo,  HTServo,  HTServo,  HTMotor)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S4,     HTANG,          sensorNone)
#pragma config(Motor,  mtr_S1_C4_1,     runBelt,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     goalLift,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     tubeLift,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     driveR,        tmotorTetrix, openLoop, reversed, driveRight)
#pragma config(Motor,  mtr_S2_C2_2,     driveL,        tmotorTetrix, openLoop, driveLeft)
#pragma config(Servo,  srvo_S1_C1_1,    clampL,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    pushL,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    liftL,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    intake,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_1,    clampR,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    pushR,                tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    liftR,                tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo12,              tServoNone)
#pragma config(Servo,  srvo_S1_C3_1,    beltGuard,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    headR,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    headL,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo16,              tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo17,              tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo18,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "auto_tasks.h"



/////Moving down the ramp/////

task main()
{
	initializeRobot();
	waitForStart();
	moveStraight(175.5901293, 20, 30);
	moveSpin(PI/2, 100);
	moveStraight(19.59401913, 0, 0);
	moveSpin(PI/2, 100);
	moveStraight(187.7785531, 0, 0);
	moveSpin(PI/3, 100);
	moveStraight(117.5657193, 0, 0);
	servo[clampL] = 145;
	servo[clampR] = 105;
	moveSpin((7 * PI)/4, 100);
	moveStraight(293.9142996, 0, 0);
	motor[runBelt] = 100;
	wait10Msec(100);

		/*moveStraight(175.5901293, 100); 	//Encoder value should be 6161.331
		moveSpin(28.42748652, 100); 				//It turns left with a positive speed, 90 degrees(in radians) * 7.125(half the width of the robot)
		moveStraight(19.59401913, 100); 	//Encoder value should be 687.54
		moveSpin(28.42748652, -100);				//It turns right with a negative speed
		moveStraight(187.7785531, 100); 	//Encoder value should be 6589.014
		moveSpin(18.95165768, -100); 			//Turns right at 60 degrees
		moveStraight(117.5657193, 100); 	//Encoder value should be 4125.2963
		servo[clampL] = 145;
		servo[clampR] = 105;
		moveSpin(99.49620283, -100); 			//Turns right at about 315 degrees
		moveStraight(293.9142996, 100); 	//Encoder value should be 10313.2408
		*/
}
