#pragma config(Hubs,  S1, HTServo,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Servo,  srvo_S1_C1_1,    pushR,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    pushL,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    clampR,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    clampL,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_1,    liftR,                tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    liftL,                tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

float map(float rLower, float rUpper, float dLower, float dUpper, float dVal)
{
	return (dVal - dLower) * (rUpper - rLower) / (dUpper - dLower)+rLower;
}

task main()
{
	while(true)
	{
		writeDebugStreamLine("%f, %f", map(0, 255, 0, 128, joystick.joy1_y1),map(0, 255, 128, 0, joystick.joy1_y1));
		getJoystickSettings(joystick);
		if(joy1Btn(4))
		{
			//servo[pushR] = map(5, 175, 0, 128, joystick.joy1_y1);
			//servo[pushL] = map(75, 235, 128, 0, joystick.joy1_y1);
			servo[pushR] = 175;
			servo[pushL] = 75;
		}
		else
		{
			servo[pushR] = 5;
			servo[pushL] = 235;
		}
		servo[liftR] = map(50, 255, 0, 128, joystick.joy1_y2);
		servo[liftL] = map(5, 220, 128, 0, joystick.joy1_y2);
		servo[clampR] = map(0, 255, 128, 0, joystick.joy1_y1);
		servo[clampL] = map(0, 255, 0, 128, joystick.joy1_y1);
	}
}
