#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTANG,               sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     LF,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     LB,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     RF,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     RB,            tmotorTetrix, openLoop)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "C:\Documents and Settings\Teemo Time\My Documents\Github\542_14-15\RobotC\drivers\3.x\drivers\hitechnic-angle.h"
// #include "C:\Documents and Settings\Teemo Time\My Documents\Github\542_14-15\RobotC\drivers\4.x\include\hitechnic-angle.h" //legacy

//cm measurements
float DIAMETER = 4.8; //diameter of tracking wheel
float CIRCUM = DIAMETER * PI; //circum of tracking wheel
float ROBOT_R = 10; //arbitrary robot radius
float TW_X = 3; //arb
float TW_Y = 3; //arb

//in cm
void moveForward(float forwardDist)
{
	float numberOfRotation = forwardDist/CIRCUM;
	float angleOfRotation = 360 * numberOfRotation;
	while (angleOfRotation <= HTANGreadAccumulatedAngle(HTANG)) {
		motor[LF] = 50;
		motor[LB]= 50;
		motor[RF] = 50;
		motor[RB]= 50;
	} //while
		motor[LF] = 0;
		motor[LB]= 0;
		motor[RF] = 0;
		motor[RB]= 0;
} //void moveForward

task main ()
{
	moveForward(4);
}
