#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTANG,               sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     LF,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     LB,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     RF,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     RB,            tmotorTetrix, openLoop)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//cm measurements
float DIAMETER = 4.8;
float ROBOT_R = 10; //arbitrary robot radius
float TW_X = 3; //arb
float TW_Y = 3; //arb

void moveForward(float t)
{

}

task main ()
{

}
