#pragma config(Sensor, S1,     sonarSensor,    sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	clearTimer(T1); //reset timer
	while(true){
		while(time1[T1] > 200) { //set timer to 100 so it doesn't overflow
			writeDebugStreamLine("%d", SensorValue(sonarSensor)); //display sonar sensor in robotC debug stream
			clearTimer(T1); //reset timer
		} //while time1
	}//while true
} //task
