#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTANG,               sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     LF,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     LB,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     RF,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     RB,            tmotorTetrix, openLoop)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-angle.h"
// #include "C:\Documents and Settings\Teemo Time\My Documents\Github\542_14-15\RobotC\drivers\4.x\include\hitechnic-angle.h" //legacy

//cm measurements
const float DIAMETER = 4.8; //diameter of tracking wheel
const float CIRCUM = DIAMETER * PI; //circum of tracking wheel

void setAllMotors(int power)
{
	motor[LF] = power;
	motor[LB]= power;
	motor[RF] = power;
	motor[RB]= power;
}
//in cm
void moveForward(float forwardDist)
{
	float numberOfRotation = forwardDist/CIRCUM;
	float angleOfRotation = 360 * numberOfRotation;
	while (angleOfRotation <= HTANGreadAccumulatedAngle(HTANG)) {
		setAllMotors(50);
	} //while
	setAllMotors(0);
} //void moveForward

task main ()
{
	moveForward(4);
}
