#pragma config(Sensor, S1,     sensorEOPD,     sensorAnalogActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-eopd.h"

task main()
{
	eraseDisplay();
	tHTEOPD eopdSensor;

	initSensor(&eopdSensor, S1);

	while(true)
	{
		eopdSensor.shortRange = false;
		configSensor(&eopdSensor);
		readSensor(&eopdSensor);
		displayCenteredTextLine(3, "%d", eopdSensor.processed);
		wait1Msec(100);

	}
	/*
	//Old EOPD program used to check EOPD values
	while(true)
	{
		HTEOPDsetShortRange(S1);
		writeDebugStreamLine("The EOPD value is: %d", HTEOPDreadRaw(sensorEOPD));
		wait1Msec(100);
	}*/
}
