#pragma config(Hubs,  S1, HTServo,  HTServo,  HTServo,  HTMotor)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     HTAC,           sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C4_1,     runBelt,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     goalLift,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_1,     tubeLift,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S2_C1_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     driveR,        tmotorTetrix, openLoop, reversed, driveRight)
#pragma config(Motor,  mtr_S2_C2_2,     driveL,        tmotorTetrix, openLoop, driveLeft, encoder)
#pragma config(Servo,  srvo_S1_C1_1,    clampL,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    pushL,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    liftL,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    intake,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_1,    clampR,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    pushR,                tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    liftR,                tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo12,              tServoNone)
#pragma config(Servo,  srvo_S1_C3_1,    beltGuard,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    headR,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    headL,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo16,              tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo17,              tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo18,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-gyro.h"
#include "hitechnic-accelerometer.h"

float heading = 0.0;
tHTGYRO gyroSensor;
tHTAC accelerometer;

//int Iadjusted = degree - power/10 + 1;

//make automatic calculator for these//
int x_offset = -20;
int y_offset = -5;
int z_offset = 5;
const float accelConvert = 0.049;
const float gyroConvert = PI/180.0

const float TAU = 0.8;
const float ALPHA = TAU/(TAU + 0.02);
const float ALPHA_COMP = 1.0 - ALPHA;

void sensorInit()
{
	initSensor(&accelerometer, S4);
	initSensor(&gyroSensor, S3);
	sleep(100);
	sensorCalibrate(&gyroSensor);
}

void gyro()
{
	float drift = 0.0;
	float time = 0.0;
	while(true)
	{
	while (time1[T1] < 20)
  	{sleep(20);}
 		eraseDisplay();
    time1[T1]=0;
    time += 0.02;
    readSensor(&gyroSensor);
    heading += gyroSensor.rotation * 0.02;
    drift = heading/time;
    displayTextLine(4, "Ang:%f", heading);
    displayTextLine(5, "T:%f", drift);
  }
}

void accel()
{
	while(true)
	{
		eraseDisplay();
		//atan2(accelerometer.x, accelerometer.y)
		readSensor(&accelerometer);

    displayTextLine(5, "%4d %4d %4d", accelerometer.x - x_offset, accelerometer.y - y_offset, accelerometer.z - z_offset);
		sleep(100);
	}
}

void complementaryFilter()
{
	while(true)
	{
		while (time1[T1] < 20)
  	{sleep(1);}
 		eraseDisplay();
    time1[T1]=0;
		readSensor(&gyroSensor);
		heading += gyroSensor.rotation * 0.02;
		heading *= ALPHA;
		readSensor(&accelerometer);
		heading += ALPHA_COMP * atan2(accelerometer.y - y_offset, accelerometer.x - x_offset)/gyroConvert;
		displayTextLine(4, "Ang:%f", heading);
	}
}



task main()
{
	sensorInit();
	//gyro();
	//accel();
	complementaryFilter();
	while(true)
	{}
}
